import React, { useState, createContext } from "react";

export const store = createContext();

function ArticleStore(props) {

   const [data, setData] = useState([
      // Bollywood
      {
         id: 1,
         url: 'https://static-koimoi.akamaized.net/wp-content/new-galleries/2023/10/tiger-shroffs-ganapath-trailers-vfx-roasted-by-a-graphic-artist-claims-makers-have-used-a-shutterstock-image-01.jpg',
         heading: "Tiger Shroff's Ganapath Trailer's VFX Roasted By A Graphic Artist, Claims Makers Have Used A 'Shutterstock' Image & Reveals They Might Get Sued For This!" ,
         description: "A couple of days back, the makers of Ganapath, starring Tiger Shroff, Kriti Sanon, and Amitabh Bachchan, dropped the official trailer of the film. After being in the making for a long time, the first rushes of the film were lauded by the fans and who's who of the entertainment industry. Recently, we came across a YouTube where the YouTuber, who is also a Graphic Designer, pointed out something that no fan was aware of.",
         description2: "The channel goes by the name of KibaKibi, and Shamim is the name of the YouTuber, who's an Assamese Graphic Designer. In the video, Shamim rips off the makers while revealing an intriguing detail. In the YouTube video, the YouTuber revealed that the Ganapath makers have used a Shutterstock image in the trailer, for which they might get sued for. He reveals that the image in question is for 'Editorial use only', which means that it can only be used for promotion but not for marketing. He goes on to compare Ganapath's VFX with Ayalaan while calling it the future of the film",
         description3: "Commenting on the video a Tiger Shroff fan wrote, “As a Tiger Fan..Honestly I agree with everything you Discussed.. Its been almost a Decade for him working in this Industry & he's still not learning from his Mistakes which makes me Sad.While another said, “I do agree… The best acting work Tiger has done was in “War”… Cuz it was so different from his usual stuff especially at the end! He should do more roles like this or at least try something different than his usual.”A few users joked, “No tiger shroff was harmed during the making of this video,” “Tiger Shroff has a hidden talent…He should keep it hidden.”",
         author: "Koimoi.com Team ",
         date: "October 15, 2023",
         footer: "Bollywood",
      },

      {
         id: 2,
         url: "https://static-koimoi.akamaized.net/wp-content/new-galleries/2023/10/singham-again-deepika-padukones-look-as-shakti-shetty-is-a-hawwwt-manic-badas-mess-fans-manifest-her-wedding-to-simmba-already-001.jpg",
         heading: "Singham Again: Deepika Padukone's Look As Shakti Shetty Is A 'Hawwwt Manic Bada*s Mess' & Fans Manifest Her Wedding To Simmba Already, “Bajirao Singham Ki Behen Sangram Bhalerao Ki Biwi Hai”",
         description: "In a surprising turn of events, this lazy Sunday was made into an exciting one, all thanks to Deepika Padukone dropping her look from Singham Again unannounced. The actress plays a female cop in the film, and introduced 'Shakti Shetty' with the most iconic posters from the film. Rohit Shettys cop Universe is definitely adding the best of the stars, and DP's savage look is a testimony that Ajay Devgn as Bajirao Singham, Ranveer Singh as Sangram Bhalerao aka Simmba, and Akshay Kumar as Veer Pratap Sooryavanshi along with Shakti Shetty are ready to take the audience on a riot they'll enjoy as hell.",
         description2: "Deepika Padukone, in the poster, is nailing the Khaki as if this role has been waiting for her for a long time. While her smile adds a layer of intrigue, she makes sure to look as bada*s as ever. The actress is a fire bomb ready to explode, and this glimpse from Rohit Shetty's cop Universe is definitely vouching for Singham Again's huge success.",
         description3: "Netizens dropped 10/10 comments on the poster and hailed the Piku actress for nailing this look. Redditors even dropped crazy ideas to get her married in the film. A comment read, “I wish in This Cop Universe somehow she ends up marrying Simba. They will make a crazy Jodi.” Another comment said, “Maybe she is playing villain police.” A third user wrote, “She looks absolutely manic, and I am here for it. Looks so bloody good.” A comment read, “Mother is mothering.” Another user wrote, “I honestly prefer the actors from the cop universe, just talent after talent. This looks badass! Akshay, Ajay, Ranveer, Deepika, and Kareena are just incredible. Can you believe this is the first time that Deepika and Ajay working together?”",
         author: "Koimoi.com Team",
         date: "October 15, 2023",
         footer: 'Bollywood',
      },
      {
         id: 3,
         url: "https://static-koimoi.akamaized.net/wp-content/new-galleries/2023/10/jawan-box-office-hindi-shah-rukh-khans-6th-friday-collection-is-a-monstrous-370-higher-than-baahubali-2-01.jpg",
         heading: "Jawan Box Office (Hindi): Shah Rukh Khan's 6th Friday Collection Is A Monstrous 370% Higher Than Baahubali 2, Beating Uri, Pathaan & Other Biggies Aiming For The Highest Sixth Week Record!",
         description: " Shah Rukh Khan's Jawan is a beast who can no longer be tamed. While the film refuses to slow down at the Box Office, the sixth Friday brought a monstrous leap, registering great numbers. The film outshone all other biggies and gorged on the platter served by the National Cinema Day. Atlee's action- biggie collected more than 5 crore on the 37th day.Sixth Friday, to be precise.The Hindi version collected a humongous 4.85 crore, breaking all the old records present in the book!",
         description2: "While the film collected close to 5 crore in Hindi 37 days after its release, it left behind all the biggies like Baahubali 2, Gadar 2, Pathaan, and interestingly, Uri: The Surgical Strike, which earned the top place in the records of the biggest sixth-Friday collection. While Uri: The Surgical Strike collected a massive 2.53 crore on its sixth Friday, Pathaan collected 1.07 crore, and Gadar 2 collected close to 1 crore but not touching the mark. However, as Jawan closed at almost 5 crore on the first day of the sixth week, it collected almost 5 times that of Baahubali 2.",
         description3: " Baahubali 2 collected 1.03 crore on the sixth Friday and closed the sixth week at 5.35 crore. Jawan definitely is beating this number as it has reached almost there entirely on the first day of the sixth week itself. While Jawan collected almost 370% higher than Prabhas's Baahubali 2 on the sixth Friday.The next aim of the film is to beat the sixth- week collection in the history of the Hindi Box Office. The record is still held by Vicky Kaushal's Uri: The Surgical Strike, which collected almost 11.59 crore in week 6. Next in line stands Pathaan at number 2, with 8.11 crore collected in week 6. Even Ajay Devgn's Drishyam 2 has a spot in the top 5 with 6.02 crore, and Gadar 2's week 6 stands at 4.5 + crore.",
         author: "Koimoi.com Team",
         date: "October 15, 2023",
         footer: 'Bollywood'
      },
      {
         id: 4,
         url: "https://www.hindustantimes.com/ht-img/img/2023/10/18/550x309/raj_kundra_1697629632125_1697629645621.png",
         heading: "UT69 trailer: Shilpa Shetty's husband Raj Kundra plays himself, gives glimpse of his life inside jail",
         description: "Shilpa Shetty's husband and entrepreneur Raj Kundra's upcoming film UT69 will be released on November 3. The trailer for UT69 dropped on Wednesday. The film, which features Raj in the lead role, is based on his life. The trailer gives a glimpse of Raj's experience in Mumbai's Arthur Road Jail because of his alleged involvement in a pornographic content case. ",
         description2: "From being recognised as Shilpa Shetty's husband or a 'Bigg Boss contestant', Raj struggles to adjust to constant ridicule by other inmates and police personnel inside the jail populate the trailer. Raj, who makes his acting debut in the film, also faces a stampede-like situation at one point. The trailer also shows the unexpected friendships Raj forms inside jail.",
         description3: "Raj was arrested in July 2021 for allegedly producing pornographic videos and was granted bail in September in the same year. He was booked under relevant sections of the Indian Penal Code, the Indecent Representation of Women (Prevention) Act and the Information Technology Act. The makers wrote along with the trailer on YouTube, “UT69 takes a satirical look into the real-life incidents of businessman Raj Kundra's days spent in Arthur Road jail. He recalls this period as his most difficult time. The film depicts this chapter of his life and is based on a true story.”",
         author: "Koimoi.com Team",
         date: "October 16, 2023",
         footer: "Bollywood",
      },
      {
         id: 5,
         url: "https://www.hindustantimes.com/ht-img/img/2023/10/18/550x309/ranbir_kapoor_national_film_awards_1697597348603_1697597348859.jpg",
         heading: "Ranbir Kapoor asks photographers to be careful as they surround Waheeda Rehman: 'He is doing what his father used to'",
         description: "Ranbir Kapoor was by Alia Bhatt's side as she received her first National Film Award for Best Actor in Delhi on Tuesday. The couple was seated in the second row with veteran actor Waheeda Rehman in the front row. At one moment during the event, Ranbir interfered as paparazzi surrounded Waheeda to click her and even started pushing the table placed in front of her. Standing up for Waheeda, who was honoured with the Dadasaheb Phalke Award at the event, Ranbir stood up from his seat and asked photographers to be careful.",
         description2: "A video from the National Film Awards ceremony has surfaced online and fans couldn't stop praising Ranbir for his gesture in the comments section. A photographer can also be heard saying in the video, “Arey yar dhakka mukki, table aage jara hai yar, kya kar rahe ho aap log (why are you pushing, the table is moving, what are you doing)?”",
         description3: "A fan commented on the video, “That's called upbringing..” Another said, “Gud gesture by RK, old lady is sitting.” Comparing him to his late father and actor Rishi Kapoor, a fan also commented, “He is doing what he's father use to.” “Ranbir is cute man,” reacted one more fan. “Such a gentleman,” read yet another comment. On a lighter note, many also asked why did he wear sunglasses during the ceremony inside Vigyan Bhawan. “Why is he wearing sun glass,” read one of many such comments. A person exclaimed, “Ander bhi black glares (black glares even inside a room)!”",
         author: "Koimoi.com Team",
         date: "October 16, 2023",
         footer: "Bollywood",
      },
      {
         id: 6,
         url: "https://www.hindustantimes.com/ht-img/img/2023/10/18/550x309/cocktail_1697641246411_1697641268892.jpg",
         heading: "Saif Ali Khan, Deepika Padukone, Diana pose in BTS stills from Cocktail's London shoot; Sharmila Tagore makes cameo",
         description: "Saif Ali Khan's sister Saba has shared behind-the-scenes stills from the actor's 2013 romantic comedy Cocktail, directed by Homi Adajania. The stills feature not only the lead trio, including Deepika Padukone and Diana Penty, but also Saif and Saba's mother and veteran actor Sharmila Tagore. (Also Read: Kareena Kapoor shares adorable pic with Saif Ali Khan on their wedding anniversary: 'Forever kinda love')",
         description2: "In two of the three pictures shared by Saba on her Instagram account on Wednesday, Saif, Deepika and Diana are sitting under a tree. The three are seen having a candid moment, sporting smiles, and shivering in the cold of London. In one of the pictures, a wide shot shows spotboys shielding the actors from the London sun between shots. From their costumes and the setting, the stills seem to be from the shoot of their popular song from the film, Daaru Desi.",
         description3: "In the first picture shared by Saba, she's seen posing with her family, Saif and Sharmila, on the sets of Cocktail in London. Saif is wearing a blue woollen jacket and matching denims, with a beige woollen scarf. Saba is in a dark blue denim jacket with a red woollen scarf wrapped around her neck. Sharmila is wearing a black woollen jacket with silver earrings. Saba wrote in the caption of her throwback post, “Cocktail....! Collecting memories (sparkle emoji) Shooting in London....:) Those were the days ....”",
         author: "Koimoi.com Team",
         date: "October 16, 2023",
         footer: "Bollywood",
      },
      {
         id: 7,
         url: "https://www.hindustantimes.com/ht-img/img/2023/10/19/550x309/tiger_1697697345382_1697697345703.png",
         heading: "Tiger Shroff joins Rohit Shetty's cop universe with Singham Again, goes shirtless as ACP Satya",
         description: "Tiger Shroff is the latest addition to Rohit Shetty's cop universe. On Thursday, the actor shared his first glimpse as ACP Satya from Singham Again. He received a warm welcome from Akshay Kumar and Ranveer Singh. Tiger took to his social media handle and dropped multiple photos of himself in the uniform. Flaunting his ripped physique in all, Tiger is seen posing with a gun in the first picture. The next one has him shirtless while the last one is a closer look at his new avatar.",
         description2: "Sharing the posters, Tiger wrote, \"ACP Satya reporting on duty Singham sir .\" Ranveer Singh wrote, “He is the truth. He is immortal. Special Task Force Officer ACP Satya, reporting for duty! Welcome to the squad…. The special one, Tiger 'The Phenom' Shroff!” “Welcoming my brother from another mother, @tigerjackieshroff as ACP Satya to the squad,” said Akshay Kumar.Reacting to Tiger's look, a fan wrote in the comment section, “Omg what It's a surprise Tiggy love you.So excited to meet Satya soon.” “Ek number,” added another one.",
         description3: "Previously, a report of Pinkvilla claimed that Tiger would have a special cameo appearance in Singham Again. A source said, \"It's a cameo appearance for Tiger Shroff in Singham Again and Rohit plans to introduce him as a new cop to the universe. Much like his Singham, Simmba, and Sooryavanshi, Tiger Shroff too will have his own distinct identity in the cop universe with traits unique to his own personality.” Tiger will be seen joining Ajay Devgn, Akshay Kumar and Ranveer Singh in the film. “It's a schedule of combination dates with Singham, Simmba and Sooryavanshi.” “He has some solo portions too in Singham Again, which eventually leads to the core conflict. ",
         author: "Koimoi.com Team",
         date: "October 17, 2023",
         content: "1",
      },
      {
         id: 8,
         url: "",
         heading: "",
         description: "",
         description2: "",
         description3: "",
         author: "Koimoi.com Team",
         date: "October 17, 2023",
         footer: "BollywoodTP",
         content: "2",
      },
      {
         id: 9,
         url: "",
         heading: "",
         description: "",
         description2: "",
         description3: "",
         author: "",
         date: "",
         footer: "BollywoodTP",
      },
      {
         id: 10,
         url: "",
         heading: "",
         description: "",
         description2: "",
         description3: "",
         author: "",
         date: "",
         footer: "BollywoodTP",
      },
      {
         id: 11,
         url: "",
         heading: "",
         description: "",
         description2: "",
         description3: "",
         author: "",
         date: "",
         footer: "",
      },
      {
         id: 12,
         url: "",
         heading: "",
         description: "",
         description2: "",
         description3: "",
         author: "",
         date: "",
         footer: "",
      },
      {
         id: 13,
         url: "",
         heading: "",
         description: "",
         description2: "",
         description3: "",
         author: "",
         date: "",
         footer: "",
      },
      {
         id: 14,
         url: "",
         heading: "",
         description: "",
         description2: "",
         description3: "",
         author: "",
         date: "",
         footer: "",
      },
      // technology
      {
         id: 15,
         url: "https://images.indianexpress.com/2023/10/minecraft-featured.jpg?resize=720,405?w=640",
         heading: "As Minecraft crosses 300 million copies, here are 5 fun facts about the most popular game on Earth",
         description: "Minecraft, the 3D sandbox video game that lets you create and destroy blocks in a virtual world, has just reached a staggering 300 million copies sold worldwide. That's more than any other single game in history, including Grand Theft Auto V, which has sold 'only' 185 million copies as of August 2023. The only franchise that can rival Minecraft is Super Mario, which has sold over 800 million games across its multiple titles. But Minecraft is unique in that it's playable on almost any platform you can think of.",
         description2: "The world of Minecraft is so vast that it dwarfs our own planet. The potential map size of Minecraft is about 60,000 km by 60,000 km, which is roughly four times the surface area of Earth. That means you can walk for days and days without ever reaching the edge of the world. And if you think that's impressive, wait until you hear this: there's a project called Build the Earth that aims to recreate the entire Earth in Minecraft.Using satellite data and a lot of dedication, the project hopes to replicate every natural and man- made feature on our planet, from the Grand Canyon to the Eiffel Tower.",
         description3: "Minecraft's creator, Markus Persson, also known as Notch, has a special avatar in the game. When he dies, he drops an apple. He's the only player in the game who has this unique feature. The apple is also a very powerful item in the game, known as an Enchanted Apple or a Notch Apple. It gives you several buffs, such as regeneration, fire resistance and absorption.",
         author: "Zohaib Ahmed",
         date: "October 17, 2023",
         footer: "Technology",
      },
      {
         id: 16,
         url: "https://images.indianexpress.com/2023/10/samsung-galaxy-s23-fe-review-featured.jpg?resize=720,405?w=640",
         heading: "Galaxy S23 FE review: Signature Samsung experience at non-flagship price",
         description: "Samsung's S series continues to dominate the world of Android flagships, with a premium price tag to match. But not everyone can afford to splurge on the latest and greatest Galaxy phone, even if they love Samsung's ecosystem of devices. That's why Samsung offers the Fan Edition lineup of smartphones that offer many of the same features and benefits but at a much more reasonable cost. The specs are so good on paper, in fact, that it made us question whether buying the Galaxy S23 is even worth it.We're talking about the Samsung Galaxy S23 FE, of course, and here are some reasons why we think the phone challenges the need for flagship spending.",
         description2: "The Galaxy S23 FE is a close cousin of the Galaxy S23 and Galaxy S23+, sharing the same triple camera setup at the back that gives it a distinctive 'Samsung' look that you can recognise from a mile away. Samsung calls it the “floating camera” design and it's very sleek and simple, with no unnecessary camera specs printed on the back of the phone. This design is now common across all Samsung phones, but the Galaxy S23 FE has something extra: a Gorilla Glass 5 back. This, along with the aluminium frame, makes the phone feel solid and premium in the hand.",
         description3: "But while the phone looks and feels premium, it is not very comfortable to hold. The aluminium frame has a slight curve, but it does not merge smoothly with the glass on both sides. The edges are sharp and they dig into your palm, which can get irritating after some time. You will need a case if you like to use your phone for long hours. This was not an issue with the Galaxy S series as far as I remember, so it seems that Samsung has deliberately tried to create some difference between the series in terms of in-hand comfort. On the front, you can see more signs of cost-cutting - the Galaxy S23 FE's display has thick bezels all around. In fact, they are thicker than its predecessor (Galaxy S21 FE). They are not too annoying, but they are still quite noticeable compared to what other phones offer at this price.",
         author: "Zohaib Ahmed",
         date: "October 17, 2023",
         footer: "Technology",
      },
      {
         id: 17,
         url: "https://images.indianexpress.com/2023/10/chatgpt-hallucination-featured.jpg?w=640",
         heading: "Is ChatGPT unreliable? Here are 5 ways to improve accuracy & prevent hallucinations",
         description: "AI chatbots are becoming more popular and powerful, thanks to advances in natural language processing and deep learning. They can help us with various tasks, such as booking flights, ordering food, or answering questions. However, they are not perfect. Sometimes, they can produce responses that are inaccurate, irrelevant, or even nonsensical. This is called “hallucination”, and it happens when the AI model generates something that is not based on reality or logic. Hallucination can be a serious problem, especially when we rely on AI chatbots for important decisions or information.Imagine if you asked it for financial tips, and it suggested you to invest in a Ponzi scheme.Or if you asked it for historical facts, and it made up some events that never happened.",
         description2: "One of the main causes of hallucination is ambiguity. When you use complex or vague prompts, the AI model may not understand what you want or what you mean. It may try to guess or fill in the gaps, resulting in inaccurate or irrelevant responses. To avoid this, you should use simple, direct language when you communicate with AI chatbots. Make sure your prompts are clear, concise, and easy to understand. Avoid using jargon, slang, idioms, or metaphors that may confuse the AI model.",
         description3: "Sometimes, AI can make up stuff when it does not have a clear sense of its identity or purpose. It may try to imitate human behaviour or personality, which can lead to errors or inconsistencies. It may also try to 'impress' you by making up things that are not true or realistic. To prevent this, you should give the AI a specific role - and tell it not to lie.A role defines what the AI model is supposed to do or be, such as a teacher, a friend, a doctor, or a journalist.A role also sets some expectations and boundaries for the AI model's behaviour and responses.",
         author: "Zohaib Ahmed",
         date: "October 12, 2023",
         footer: "Technology",
      },
      {
         id: 18,
         url: "https://images.indianexpress.com/2023/10/cmf-buds-pro-review-featured.jpg?w=640",
         heading: "CMF Buds Pro review: A quirky, more affordable alternative to the Nothing Ear series",
         description: "The AirPods have virtually set the standard for how true wireless earbuds should look like, with their pill-shaped case and stem-like design. But some brands are not afraid to challenge the norm and experiment with different shapes and materials. Nothing is one of them, with its Ear series of earbuds that feature a transparent body and a distinctive form factor. The brand has a flair for design, which is also evident in its subbrand CMF's latest product. The CMF Buds Pro are among the most quirky and fancy earbuds we have ever seen, but they have more to offer than just looks.Read on to find out why we are impressed by them.",
         description2: "CMF sure was pretty serious about its whole “colour, material, and finish” mojo with the Buds Pro because the earbuds check all these boxes - well, almost if you dig the black colour that I was lent. These earbuds also come in white (which instantly caught my eye when I saw the promotional images) and bright orange for those who like to make a statement. I especially liked the shape and size of the case, which has a circular design that resembles a makeup product, like a blush compact.",
         description3: "One thing that these earbuds nail is the matte finish they sport. It’s not easy to pull off when the choice of materials is low-quality and only makes things worse. But CMF has done a good job here. The earbuds also feel premium thanks to the weight of the case and its thickness. The lid, for example, has a nice heft to it and closes with a satisfying and loud click. However, the downside of the black colour and the matte finish is that these earbuds are prone to scratches. In fact, I could easily scratch them with my fingernails. That's why I would suggest opting for the white or orange colours instead.",
         author: "Zohaib Ahmed",
         date: "October 13, 2023",
         footer: "Technology",
      },
      {
         id: 19,
         url: "https://images.indianexpress.com/2023/10/whatsapp-logo-featured-express.jpg?w=640",
         heading: "WhatsApp's coolest 2023 updates: 10 new features you don't want to miss",
         description: "WhatsApp may have almost 3 billion users, but it's not a big cash cow for Meta as you might expect. Unlike Instagram, which rakes in money from ads, WhatsApp makes only a tiny fraction of the revenue. But Meta has some plans to change that. Meta wants to make money by bringing businesses to WhatsApp Business, and it has been working hard to do that.Just look at 2023, which saw so many new features on WhatsApp that it's hard to keep up.But don't worry, we have got you covered with this article.",
         description2: "If you want to share your thoughts with your friends without the hassle of typing, WhatsApp has got you covered with its new voice status feature. Now you can record and post voice messages on your status - they stay up for 24 hours just like Instagram stories. All you have to do to create one is go to the Status tab, tap the pencil icon, and press and hold the mic icon.",
         description3: "Have you ever lost track of an important chat in the sea of messages on WhatsApp? That won't be happening again with the new pin messages feature that lets you keep up to three chats at the top of your list for easy access. To pin a chat, just tap and hold it, and then tap Pin chat on Android. On iOS, you can do the same by simply swiping right on the chat. We all make mistakes sometimes, especially when we are typing fast on WhatsApp. Maybe you misspelt a word, forgot to add something important, or accidentally sent a message to the wrong person. Don't worry, WhatsApp has got your back with its new edit messages feature. This feature lets you edit any message you have sent within 15 minutes of sending it. Just long-press on the message and choose Edit from the menu.",
         author: "Zohaib Ahmed",
         date: "October 12, 2023",
         footer: "Technology",
      },
      {
         id: 20,
         url: "https://images.indianexpress.com/2023/10/galaxy-s23-fe-vs-galaxy-s23-featured.jpg?w=640",
         heading: "Samsung Galaxy S23 FE vs Galaxy S23: Which model reigns supreme?",
         description: "After making us wait for what seemed like an eternity, Samsung finally unveiled its latest offering in the coveted FE series of smartphones, the Galaxy S23 FE, on Wednesday. The new device boasts improvements in every aspect but also comes with a heftier price tag that puts it closer to its more premium sibling, the Galaxy S23. This raises an interesting question: is the Galaxy S23 worth the extra bucks? And if so, what are you getting in return for shelling out more? We try to answer these questions in this article.",
         description2: "The Samsung Galaxy S23 FE has a 6.4-inch AMOLED display with a 120Hz refresh rate and a peak brightness of 1,450 nits. It's powered by the Exynos 2200 chip which gets its juice from a 4,500 mAh battery that fills up at 25W. For photography, the phone has a 50MP + 8MP telephoto 3x optical zoom + 12MP ultrawide at the rear and a 10MP snapper upfront. Other features include Gorilla Glass 5 at the back and front with an aluminium frame in the middle and an IP68 rating.",
         description3: "Meanwhile, the Samsung Galaxy S23 has a 6.1-inch AMOLED display with a 120Hz refresh rate and a peak brightness of 1,750 nits. It's powered by the Snapdragon 8 Gen 2 chip which gets its juice from a 3,900 mAh battery that fills up at 25W. For photography, the phone has a 50MP + 10MP telephoto 3x optical zoom + 12MP ultrawide at the rear and a 10MP snapper upfront. Other features include Gorilla Glass Victus 2 at the back and front with an aluminium frame in the middle and an IP68 rating.",
         author: "Zohaib Ahmed",
         date: "October 8, 2023",
         footer: "Technology",
      },
      {
         id: 21,
         url: "",
         heading: "",
         description: "",
         description2: "",
         description3: "",
         author: "",
         date: "",
         footer: "",
      },
      {
         id: 22,
         url: "",
         heading: "",
         description: "",
         description2: "",
         description3: "",
         author: "",
         date: "",
         footer: "",
      },
      {
         id: 23,
         url: "",
         heading: "",
         description: "",
         description2: "",
         description3: "",
         author: "",
         date: "",
         footer: "",
      },
      {
         id: 24,
         url: "",
         heading: "",
         description: "",
         description2: "",
         description3: "",
         author: "",
         date: "",
         footer: "",
      },
      {
         id: 25,
         url: "",
         heading: "",
         description: "",
         description2: "",
         description3: "",
         author: "",
         date: "",
         footer: "",
      },
      {
         id: 26,
         url: "",
         heading: "",
         description: "",
         description2: "",
         description3: "",
         author: "",
         date: "",
         footer: "",
      },
      {
         id: 27,
         url: "",
         heading: "",
         description: "",
         description2: "",
         description3: "",
         author: "",
         date: "",
         footer: "",
      },
      {
         id: 28,
         url: "",
         heading: "",
         description: "",
         description2: "",
         description3: "",
         author: "",
         date: "",
         footer: "",
      },
      {
         id: 29,
         url: "",
         heading: "",
         description: "",
         description2: "",
         description3: "",
         author: "",
         date: "",
         footer: "",
      },
      {
         id: 30,
         url: "",
         heading: "",
         description: "",
         description2: "",
         description3: "",
         author: "",
         date: "",
         footer: "",
      },
      {
         id: 4,
         url: "",
         heading: "",
         description: "",
         description2: "",
         description3: "",
         author: "",
         date: "",
         footer: "",
      },
      {
         id: 4,
         url: "",
         heading: "",
         description: "",
         description2: "",
         description3: "",
         author: "",
         date: "",
         footer: "",
      },
      {
         id: 4,
         url: "",
         heading: "",
         description: "",
         description2: "",
         description3: "",
         author: "",
         date: "",
         footer: "",
      },
      {
         id: 4,
         url: "",
         heading: "",
         description: "",
         description2: "",
         description3: "",
         author: "",
         date: "",
         footer: "",
      },
      {
         id: 4,
         url: "",
         heading: "",
         description: "",
         description2: "",
         description3: "",
         author: "",
         date: "",
         footer: "",
      },

   ]);

   return (
      <store.Provider value={[data, setData]}>
         {props.children}
      </store.Provider>
   );
}

export default ArticleStore;
